#!/bin/bash
################################################################################
#
# A utility script to check current Quick Box version
# as well as included commands and their use.
#
################################################################################
PROGNAME="Quick Box"
VERSION="2.0.7"
FILES=()
#################################################################################
#Script Console Colors
black=$(tput setaf 0); red=$(tput setaf 1); green=$(tput setaf 2); yellow=$(tput setaf 3); 
blue=$(tput setaf 4); magenta=$(tput setaf 5); cyan=$(tput setaf 6); white=$(tput setaf 7); 
on_red=$(tput setab 1); on_green=$(tput setab 2); on_yellow=$(tput setab 3); on_blue=$(tput setab 4); 
on_magenta=$(tput setab 5); on_cyan=$(tput setab 6); on_white=$(tput setab 7); bold=$(tput bold); 
dim=$(tput dim); underline=$(tput smul); reset_underline=$(tput rmul); standout=$(tput smso); 
reset_standout=$(tput rmso); normal=$(tput sgr0); alert=${white}${on_red}; title=${standout}; 
sub_title=${bold}${yellow}; repo_title=${black}${on_green};
#################################################################################

function _string() { perl -le 'print map {(a..z,A..Z,0..9)[rand 62] } 0..pop' 15 ; }

error_exit() {
  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
  exit 1
}

graceful_exit() {
    exit
}

usage() {
    echo
    echo -e "   #########################"
    echo -e "   Quick System Commands"
    echo -e "   #########################"
    echo
    echo -e "   Usage: ${green}disktest${normal} - perform a quick r/w test of your disk"
    echo -e "   Usage: ${green}fixhome${normal} - quickly adjusts /home directory permissions"
    echo
    echo
    echo -e "   #########################"
    echo -e "   Admin Commands"
    echo -e "   #########################"
    echo
    echo -e "   Usage: ${green}createSeedboxUser${normal} - create user and password and assign their diskspace"
    echo -e "   Usage: ${green}deleteSeedboxUser${normal} - easily delete a selected user"
    echo -e "   Usage: ${green}setdisk${normal} - sets users disk quota"
    echo -e "   Usage: ${green}changeUserPass${normal} - allows you to change a users password"
    echo -e "   Usage: ${green}upgradeBTSync${normal} - upgrade BTSync to newest version when available"
    echo
    echo
    echo -e "   #########################"
    echo -e "   User Commands"
    echo -e "   #########################"
    echo
    echo -e "   Usage: ${green}reload${normal} - allows user to reload their services (rtorrent and irssi)"
    echo -e "   Usage: ${green}screen -fa -dmS rtorrent rtorrent${normal} - allows user to restart/remount rtorrent from SSH"
    echo -e "   Usage: ${green}screen -fa -dmS irssi irssi${normal} - allows user to restart/remount irssi from SSH"
    echo
    echo
}

function _help_message() {
  cat <<- _EOF_
  $PROGNAME ver. $VERSION

  You are currently running $PROGNAME ver. $VERSION.
  Check the Quick Box Repo to stay current.

  Below are some additional commands that you will
  find useful with your Quick Box Seedbox.

  $(usage)

_EOF_
  return
}

clear
_help_message